#!/bin/bash 
database="/root/usuarios.db"
if [ ! -f "$database" ]; then
	echo  -e "\E[38;5;15mARCHIVO $database NO ENCONTRADO" ; echo ""
	exit 1
else
	echo ""
	echo  -e "\E[38;5;15mLISTA DE USUARIOS Y SUS LIMITES:"
	echo ""
	_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
	i=0
	unset _userPass
	while read _user; do
		i=$(expr $i + 1)
		_oP=$i
		[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
		if [[ "$(grep -wc "$_user" $database)" != "0" ]]; then
			limit=$(grep -w "$_user" $database |cut -d' ' -f2)
		else
			limit='1'
		fi
		l_user=$(echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m")
        lim=$(echo -e "\033[1;33mLimite\033[1;37m: $limit")
        printf '%-65s%s\n' "$l_user" "$lim"
		_userPass+="\n${_oP}:${_user}"
	done <<< "${_userT}"
	echo ""
	num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
	echo -ne "\033[1;32mDIGITE O SELECCIONE UN USUARIO \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
	usuario=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
    if [[ -z $option ]]; then
        echo  -e "\E[38;5;15mUSUARIO VACIO O NO EXISTENTE"
		exit
	elif [[ -z $usuario ]]; then
		echo  -e "\E[38;5;15mUSUARIO VACIO O NO EXISTENTE"
		exit 1
	else
		if cat /etc/passwd |grep -w $usuario > /dev/null; then
			echo -ne "\n\033[1;32mNUEVO LIMITE PARA EL USUARIO \033[1;33m$usuario\033[1;37m: "; read sshnum
			if [[ -z $sshnum ]]
			then
				echo  -e "\E[38;5;15mNÚMERO INVÁLIDO!" 
				exit 1
			else
				if (echo $sshnum | egrep [^0-9] &> /dev/null)
				then
					echo  -e "\E[38;5;15m NÚMERO INVÁLIDO!"
					exit 1
				else
					if [[ $sshnum -lt 1 ]]
					then
						echo  -e "\E[38;5;15mESCRIBE UN NÚMERO MAYOR QUE CERO!" 
						exit 1
					else
						grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/a
						sleep 1
						mv /tmp/a /root/usuarios.db
						echo $usuario $sshnum >> /root/usuarios.db
						echo  -e "\E[38;5;15mLIMITE APLICADO PARA EL USUARIO $usuario ES $sshnum " 
						sleep 2
						exit
					fi
				fi
			fi			
		else
			echo  -e "\E[38;5;15mEL USUARIO $usuario NO FUE ENCONTRADO"
			exit 1
		fi
	fi
fi